#!/usr/bin/env bash
echo "!----- Syncing files to Dropbox -----!"
./dropbox upload /app/panel/data/users/* /mc-server1/users/
sleep 3
zip -r backup.zip server/*
sleep 3
./dropbox upload backup.zip /mc-server1/server
rm backup.zip
